### ISSUE TITLE
Release 0.1a - Hard failure with no config file

### ISSUE THREAD

**Issue by itfs-steve** [CallMeSteve297/engineercollect#1]
**Expected behaviour**
config file not found, is downloaded from Github, continues as usual

**Actual behaviour**
config file not found, errors out with file not found. File isn't downloaded

**Example**
<img width="580" alt="image" src="https://user-images.githubusercontent.com/122524858/235974320-c943cbfe-d08e-42ca-a35d-714cbe6766d0.png">

**Environment**
Only occurs when using the exe, running it from source works fine.

**Comment by CallMeSteve297** [comment]
This has been fixed in v0.2a
